name: Manual Deploy Network Configuration

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run deployment script
      run: |
        python config/manual_wf/deploy_config.py | tee deployment.log

    - name: Upload deployment logs
      uses: actions/upload-artifact@v4
      with:
        name: deployment-logs
        path: deployment.log
