name: Test Configuration Changes

on:
  push:
    branches:
      - main
    paths:
      - 'config/**/*'         # Only run if files in the config directory change
      - 'tests/**/*'          # Only run if files in the tests directory change
  pull_request:
    branches:
      - main
    paths:
      - 'config/**/*'         # Only run if files in the config directory change
      - 'tests/**/*'          # Only run if files in the tests directory change

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Generate configuration files (before and after change)
      run: |
        # You can manually add or modify the configuration files as needed.
        # Here we just copy them for testing
        echo "parameter1=value1" > config/config_file_before_change.txt
        echo "parameter2=value2" >> config/config_file_before_change.txt

        echo "parameter1=value1" > config/config_file_after_change.txt
        echo "parameter2=value2" >> config/config_file_after_change.txt
        echo "parameter3=value3" >> config/config_file_after_change.txt

    - name: Run pytest tests
      run: |
        pytest tests/test_config_changes.py
