name: Use Secret with API

on:
  push:
    branches:
      - main

jobs:
  use-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Read and process config file
      run: |
        # Read the content of the file
        CONFIG_CONTENT=$(cat rendered_config.txt)
        echo "Config content: $CONFIG_CONTENT"

    - name: Use secret to authenticate API request
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        # Use the secret to authenticate an API (not required for JSONPlaceholder)
        echo "Using API_KEY: $API_KEY"
        
        # Make a GET request to JSONPlaceholder API
        RESPONSE=$(curl -s https://jsonplaceholder.typicode.com/posts/1)
        echo "API response: $RESPONSE"
