name: Append Secret to Config File

on:
  push:
    branches:
      - main

jobs:
  append-secret:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Read and append secret to config file
      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: |
        # Read the content of the file
        CONFIG_CONTENT=$(cat rendered_config.txt)
        echo "Original config content: $CONFIG_CONTENT"
        
        # Append the secret to the content
        UPDATED_CONTENT="$CONFIG_CONTENT API_KEY=$API_KEY"
        echo "Updated config content: $UPDATED_CONTENT"
        
        # Write the updated content back to the file
        echo "$UPDATED_CONTENT" > rendered_config.txt

    - name: Commit and push changes
      run: |
        git add rendered_config.txt
        git commit -m "Append API_KEY to rendered_config.txt"
        git push
